InitRegistratoPage
dmowski/profolio pull request #2
Opened 2021-12-08 10:53 UTC by dllsc

2021-12-08 13:00 UTC, G-Milevski commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
я думаю папку .idea надо добавить в gitignore

2021-12-08 13:00 UTC, G-Milevski commented on main-services/welcome-page/src/App.tsx
> +{/*<RegistrationPage/>*/}
я считаю что коментированный код хранить в репозитоии не очень хороший подход

2021-12-08 13:00 UTC, G-Milevski commented on main-services/welcome-page/src/App.tsx
> +import RegistrationPage from './page/RegistrationPage';
при подключении линтера на ПР тут будет ошибка того что этот модуль нигде не используется.
так как его использование закоментироовано на строке 9

2021-12-08 13:00 UTC, G-Milevski commented on main-services/welcome-page/src/component/Button/Button.module.css
> +    font-size: 14px;
как насчет того, чтобы для шрифта использовать rem

2021-12-08 13:00 UTC, G-Milevski commented on main-services/welcome-page/src/component/Button/Button.tsx
> +import cn from 'classnames';
пожалуйста не используйти такие сокращения, пишите слово полностью.
так как при таком сокращении тяжело понять что этот модуль делает

2021-12-08 13:00 UTC, G-Milevski commented on main-services/welcome-page/src/page/RegistrationPage.tsx
> +      <h1 className={styles.h1}> Create Account</h1>
порчему не форма? 
Семантически вернее использовать елемент form, а не просто набор div

2021-12-08 13:00 UTC, G-Milevski commented
main-services/welcome-page/npm
main-services/welcome-page/cd
я так понимаю созданы по ошибке

2021-12-09 16:48 UTC, dmowski requested changes

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Authorization Form/AuthorizationForm.module.css
> +
Много переносов строк. Лучше оставить один перенос

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Authorization Form/AuthorizationForm.props.ts
> +  form: 'CreateAccount' | 'signIn' | 'RecoveryPassword'
Лучше использовать идентичную форму названия
'CreateAccount' | 'SignIn' | 'RecoveryPassword'

не signIn а SignIn

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Authorization Form/AuthorizationForm.tsx
> +
Лучше использовать объект
```
const components = {
  "CreateAccount": <CreateAccountAuthorizationForm/>,
  "RecoveryPassword": <RecoveryPasswordAuthorizationForm/>,
  "SignIn": <SignInAuthorizationForm/>,
};

const component = components[form] || components["SignIn"];
return component;
```

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Authorization Form/CreateAccount/CreateAccountAuthorizationForm.tsx
> +
Форматирование поехало. Много переносов

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Authorization Form/CreateAccount/CreateAccountAuthorizationForm.tsx
> +    <div className={styles.addressDivCreateAccount}>
Лучше не использовать в названиях классов названия тэгов.
просто `addressContainer`

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Authorization Form/CreateAccount/CreateAccountAuthorizationForm.tsx
> +    <div className={styles.checkboxDiv}>
Можно проще. `styles.checkbox` или `styles.checkboxContainer`. без привязки в тэгу div

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Authorization Form/RecoveryPassword/RecoveryPasswordAuthorizationForm.tsx
> +    <h1 className={styles.h1}>Password Recovery</h1>
styles.title

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Content-welcome-page/Content-welcome-page.module.css
> +.butt {
Лучше использовать полные и более понятные названия классов
.mainActionButton для примера

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Content-welcome-page/Content-welcome-page.module.css
> +.backgroundWall {
backgroundWallpaper

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Content-welcome-page/Content-welcome-page.module.css
> +.containerWall {
Удалить пустые классы

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/component/Input/Input.module.css
> +    font-family: var(--font-family);
вроде это не нужно, така это прописано в global.css

----------------

html,
body {
  margin: 0;
  padding: 0;
  color: var(--black);
  background: #E5E5E5;
  font-family: "Roboto", sans-serif; <--- тут
}

2021-12-09 16:48 UTC, dmowski commented on main-services/welcome-page/src/styles/globals.css
> +  font-family: "Roboto", sans-serif;
можно заюзать переменную 
font-family: var(--font-family);

2021-12-09 22:35 UTC, G-Milevski commented
lgtm
Пожалуйста следющие ПР делайте поменьше )))

2021-12-10 17:50 UTC, dmowski approved these changes

2021-12-10 17:50 UTC, merged