Upstream/checkbox
dmowski/profolio pull request #32
Opened 2022-03-01 12:22 UTC by suhobski

Сделал чекбокс в различных состояниях. Не делал построение группы с заголовками, текстом описания и ошибок.

Не разобрался с проблемой. Пока плохо разбираюсь в TS.
```
src\components\core\Checkbox.tsx
  Line 44:26:  Object pattern argument should be typed  @typescript-eslint/explicit-module-boundary-types
```

2022-03-02 16:21 UTC, alex-dmowski requested changes

2022-03-02 16:21 UTC, alex-dmowski commented on customer-services/admin-panel/src/components/core/Checkbox.tsx
> +  margin: 2,
лучше использовать явные величины. 2px например

2022-03-05 15:54 UTC, dmowski commented on customer-services/admin-panel/src/assets/styles/globals.css
> +}
А для чего нужно это?

2022-03-05 20:08 UTC, suhobski commented on customer-services/admin-panel/src/components/core/Checkbox.tsx
> +  margin: 2,
Поправил величины и добавил prop types

2022-03-17 20:26 UTC, closed without merging